before_script:
  - /etc/init.d/redis-server restart
  - make gitlab-ci
  - Xvfb :99 1>/dev/null 2>&1 &
  - [ -d /tmp/coverage ] && rm -rf /tmp/coverage
  - [ -f .coverage ] && rm .coverage

alltests:
  script:
    - bin/code-analysis
    - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 DISPLAY=:99 bin/test --coverage=/tmp/coverage

