language: python
python: "2.7"
sudo: false
install:
  - mkdir -p buildout-cache/downloads
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pyenchant
  - buildout -c travis.cfg buildout:develop= install download install
  - buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/coverage run -p --source=src bin/test
after_success:
  - pip install -q coveralls
  - coveralls
before_install:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
